"""room table

Revision ID: 5beee08aaf5b
Revises: 
Create Date: 2018-07-18 14:29:29.729000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5beee08aaf5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('host', sa.String(length=16), nullable=True),
    sa.Column('players', sa.String(length=256), nullable=True),
    sa.Column('gameState', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    # ### end Alembic commands ###
